### ISSUE TITLE
gpu util 과 bus_bandwidth 간에 연관성 보기(util = nvidiasmi  vs  occupancy = nvidia occupancy)

### ISSUE THREAD

**Issue by hyoonseo159357** [ddps-lab/cloud-hw-trainpred#10]
gpu util 이 점유율을 나타내는것이 아니라 bus_bandwidth 와 관련이 있는지 관련된 내용 확실히 정리하기

**Comment by hyoonseo159357** [comment]
다른 이슈에서 진행하여 해당이슈를 종료

**Comment by kmu-leeky** [comment]
다른 이슈는 어떤 이슈인거야? 링크를 달아주면 좋을것 같아.

**Comment by hyoonseo159357** [comment]
- gpu util : 1/6 ~ 1분동안 수집된 gpu util , 즉 0.1초로 수집하던 1초로 수집하던간에 고정된 시간동안 수집된 gpu util 평균을 의미.
- occupancy 즉 dcgmi 로 수집한 bandwidth : 0.1초간격으로 수집했다면 0.1초동안의 평균, 1초간격으로 수집했다면 1초동안의 평균을 의미. 

당시에 두가지 피처만 따로 보았을때 특별한 상관관계는 존재하지 않았고, nvidia-smi로 뽑은 utilizaiton 의 의미와 dcgmi로 뽑은 점유율의 차이에 대한 의문점으로 https://github.com/ddps-lab/cloud-hw-trainpred/issues/14#issue-1285177872 에서 간단히 언급하였었습니다.
