### ISSUE TITLE
1+2 시나리오) main metric 과 가장 유사한 similar metric을 찾고 인스턴스변화시 latency간에 선형적인 관계를 보이는지 분석하기

### ISSUE THREAD

**Issue by hyoonseo159357** [ddps-lab/cloud-hw-trainpred#11]
g4dn Alexnet 을 진행했다 쳤을때 동일한 인스턴스(g4dn)에서 가장 흡사한 매트릭을 찾는다.
( 흡사한 매트릭을 찾을때 사용한 항목들은 gpu util, memory util 의 특성들 ( median,average,75%등등...))

이렇게 main metric과 similar metric 간에 인스턴스별로 실험했을때의 latency 비율이 비슷한지 확인한다.
ex) main metric(g4dn) latency : main metric(p3) latency = similar metric(g4dn) : similar metric(p3) latency 이렇게 비슷한 비율을 보이는지 확인한다.

**Comment by hyoonseo159357** [comment]
**1. 우선적으로 매트릭끼리의 벡터유사도를 측정하여 가장 유사한 매트릭 5개씩을 뽑아냈습니다.** 
    
    
    1) 사용한 피처값  (전체 피처값을 사용했더니 유사도 자체가 너무 낮게 나와서 일부만을 사용함)
    
    ```
    ['utilization_gpu_mean',
     'utilization_gpu_std',
     'utilization_gpu_25',
     'utilization_gpu_50',
     'utilization_gpu_75',
     'utilization_memory_mean',
     'utilization_memory_std',
     'utilization_memory_25',
     'utilization_memory_50',
     'utilization_memory_75']
    ```
    
    2) 사용한 벡터 유사도
    
        [https://yoonseoooooo.notion.site/bca1f543186949e088c8ba933fabb6b9](https://www.notion.so/bca1f543186949e088c8ba933fabb6b9) (간단히 정리)
    
    - 코싸인 유사도
    - 유클리디안 유사도
    - 삼각형면적 유사도(TS)
    - 부채꼴면적 유사도(SS)
    - TS-SS(TS,SS유사도의 곱)


     
    3) 유사한 매트릭은 다음과같이 5개씩 (1th~ 5th) 뽑았습니다.
    (아래 예시는 TS-SS유사도로 뽑은 유사한 매트릭들, 아래 데이터프레임에서 1th = 1번째로 가장 유사한 매트릭, 1th_value = 유사도값을의미. 0에 가까울수록 유사하다.)

<img width="1696" alt="image" src="https://user-images.githubusercontent.com/50091802/172321531-4e0ee57f-4c69-4028-9718-88dd4566525e.png">
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/50091802/172322090-a4590898-244f-4119-b5c7-a27e2a527f59.png">


**2. 이렇게 뽑은 유사한 매트릭과 본래 매트릭의 인스턴스별 latency 변화가 상이한지 확인하고자 합니다..**
    
    1) 인스턴스별로 latency 변화양상이 동일한지 확인 (단순하게 크고 작은지만 확인)
(e.g. p100_MNIST_CNN_batchsize32_datasize224_total_epoch10_totaldata2000 와 가장 유사한 매트릭으로 뽑힌것이 p100_VGG19_batchsize128_datasize256_total_epoch10_totaldata2000 이라면, 이 두가지 모두 latency가 ` p3 > g4dn > p100 > g5`로 동일한가?)
    
    2) 인스턴스별로 latency 변화하는 폭이 비슷한지 확인)
(e.g. p100_MNIST_CNN_batchsize32_datasize224_total_epoch10_totaldata2000 와 가장 유사한 매트릭으로 뽑힌것이 p100_VGG19_batchsize128_datasize256_total_epoch10_totaldata2000 이라면, 이 두가지 모두 latency 비율이 `3 : 4 : 5 : 2 `로 비슷한 양상을 보이는가? )

**Comment by hyoonseo159357** [comment]
현재 비교해보고자 하는것을 그림으로 재정리

![image](https://user-images.githubusercontent.com/50091802/172330872-53a932d3-eddc-4d90-97ab-5cb5c2d3ec79.png)

**Comment by kmu-leeky** [comment]
응 윤서야 괜찮아보인다. 우선 유사도 측정을 잘했다. 지금 그림이나 사례를 봐서는 전에 이야기한 방향과 일치하는것 같아. 한가지 유사한 값들을 뽑을때 gpu 타입이 다른건 뽑히면 안된다. 예를 들어 p100_... 이런것과 g4dn_... 이런것이 같이 비슷하다고 그룹핑 되버리면 우리가 생각했던 시나리오에서 벗어날것 같거든. 이런 경우가 뽑힐수 있는지 확인해보고 내일 같이 데이터를 더 분석해보자.

**Comment by hyoonseo159357** [comment]
넵 말씀하신대로 동일한 gpu 내에서 뽑도록 하였습니다.  예를들어 p100_MNIST_CNN_batchsize32_datasize224_total_epoch10_totaldata2000 와 비슷한 매트릭을 뽑을때 p100안에서의 매트릭에서만 고르도록 진행하였습니다. 현재 도출해낸 유사도 데이터를 가지고 분석하여 정리하고자 합니다. 넵!

**Comment by hyoonseo159357** [comment]
Vector similarity 중 가장 나은값을 보이는것이 코사인 유사도였고, 비교한값은 다음과 같습니다.
- main train 과 비슷한 매트릭을 고를때, `동일한 인스턴스`에서, `동일한 모델은 제외`하고 진행
- 1.0 이 의미하는바는 4개 인스턴스에서의 latency 대소비교순서가 동일하다는뜻 ( 예를들어서 main train 에서 latency가 p3>g4dn>p100>g5이였을때 similar metric 에서 latency도 동일하게 p3>g4dn>p100>g5 이런 양상을 보였다는 뜻)
- 0.75가 의미하는바 : [3,2,1][3,2,1,0] 이런식으로 해당 인스턴스에서의 latency 값이 없을경우 4개중에서 3개만 동일하게 봄.
- 0.5가 의미하는바 : 다음과 같은 순서를 보임 [3, 0, 1, 2] | [3, 0, 2, 1]

1.00000    242
0.75000    159
0.50000    146
0.25000    128
0.00000     36
