### ISSUE TITLE
nvidia-occupancy 참조 (nvidia-smi 가 utilization이라면 nvidia-occupancy는 occupancy) - nsight, DCGM

### ISSUE THREAD

**Issue by hyoonseo159357** [ddps-lab/cloud-hw-trainpred#14]
지난번 성재님이 공유해주셨던 "Wavelet: Efficient DNN Training with Tick-Tock Scheduling" 논문에서 사용된 nvidia-occupancy을 좀더 살펴본 결과 nvidia-smi는 utiliazaion(사용률) 을 nvidia-occupancy는 occupancy(점유율)을 보여주는것을 확인하였고 occupnacy로 얻을수 있는 피처들도 추가적으로 사용할수 있으면 좋을것 같습니다.

점유(Occupancy) - nvidia occupancy : 
<img width="569" alt="image" src="https://user-images.githubusercontent.com/50091802/175851405-c88af647-94dd-4367-b988-69dbd77accbf.png">
→ 일하는시간중 실제로 일을 한 시간.(콜센터를 예시로 들면 업무시간중 전화를 받은시간)(GPU의 점유가 의미하는바는 하드웨어기능을 몇퍼센트 사용하고 있는지)

사용률(Utilization) - nvidia smi: 
<img width="512" alt="image" src="https://user-images.githubusercontent.com/50091802/175851427-1514b795-46b8-4384-adc0-222360e14954.png">
→ 총작업시간중(일정시간) 실제로 일한 시간 (콜센터 예시에서 전체 근무시간중 실제로 일한시간)(GPU에서 사용률이 의미하는바는 하나 이상의 커널이 실행된 지난 1초 동안의 시간 백분율을 의미)

추가적으로 실시간 Occupancy 정보를 nvidia-smi처럼 실시간으로 얻어낼수 있을지 조금더 살펴보고자 합니다.

**Comment by hyoonseo159357** [comment]
현재 DCGMI 에서 뽑을수 있는 전체 피처목록은 아래에서 확인할수 있습니다.

[https://docs.nvidia.com/datacenter/dcgm/1.7/dcgm-api/group__dcgmFieldIdentifiers.html](https://docs.nvidia.com/datacenter/dcgm/1.7/dcgm-api/group__dcgmFieldIdentifiers.html)

⇒ 갯수가 많아서 처음부터 모든 피처가 의미하는바를 정리하는것은 비효율적일것 같아 우선 gpu마다 지원하는피처들만 추리고, nvidia-smi 와 곂치는 피처들은 제외하고 남은 피처들을 가지고 각 피처가 의미하는바들을 정리해볼예정입니다

현재 g5, g4dn, p100 인스턴스 에서 진행시 큰문제없이 output출력까지 되는것을 확인했습니다.

- 100ms 마다 뽑아줌 ( 1000ms = 1초)
- output 은 dcgmi-log.csv 로 저장

```jsx
dcgmi dmon -d 100 -e 1001,1004,1005 > dcgmi-log.csv
```

- 하지만 전체 피처를 수집하고자 하니 에러가 발생

⇒ 한번에 뽑을수 있는 피처갯수는 128개라고 합니다. (you will not be able to collect more than 128 fields due to this limitation alone.)

⇒ 만약 수집할 피처갯수가 128개가 넘는다면 명령문을 여러개 돌려야함. 그래서 일단 현재 전체 피처들을 나누어서 수집해보고자 합니다.

**Comment by kmu-leeky** [comment]
오케이. 윤서야 그러면 nsight 는 하지말고 dcgmi 정도만 해보자. 그리고 128개 메트릭까지는 굳이 필요없지? 메트릭 갯수가 엄청 많기는 하네 ㅎㅎ 필요해 보이는것 위주로 진행을 해보자.

**Comment by hyoonseo159357** [comment]
넵 dcgmi 위주로 사용해보겠습니다. 총 373개 피처를 제공하지만 gpu에서 제공하지않는 기능과 실제로 필요한 피처를 추리면 128개 안으로 실행가능할것같습니다.
