### ISSUE TITLE
Profet A-Z 실행 (5개 GPU)

### ISSUE THREAD

**Issue by hyoonseo159357** [ddps-lab/cloud-hw-trainpred#20]
Profet 프로파일링~ 부터 실행

**Comment by hyoonseo159357** [comment]
추가로 수집한 5개 gpu를 가지고 이전에 구한 수치들을 모두 다시 구해보고자 합니다.

- [ ]  alibaba cloud에서 수집한 a10 gpu에서 device 부분에서 문제가 있음을 확인하고 재수집을 진행중입니다.
- [ ] 추가된 gpu를 포함하여 pre,raw 데이터 재구성예정
    - 이전에는 exp01~exp09 데이터를 모두 사용하였지만(프로파일링 10번수행), 추가데이터를 수집하면서 10번이 아니라 프로파일링을 1번씩 진행하여 우선적으로 모두 exp09 하나만 사용하여 비교해볼 예정입니다. 
- [ ] 이전과 동일하게 진행한후 predict mape 비교예정
- [ ] name clustering 부분에서 언급되었던 평가들을 모아서 정리예정

**Comment by hyoonseo159357** [comment]
추가한 GPU 프로파일링 결과를 더하여 name clustering 을 적용한 profet 을 처음부터 끝까지 진행하여 mape를 다시 구해보았습니다.


- 기존에는 exp01-exp09까지 10번 프로파일링한 결과를 사용하였지만, 새로운 gpu를 추가하면서 exp09하나만을 사용하여, original profet의 데이터양보다 1/10로 진행하였습니다. 
- 총 3가지 케이스를 가지고 mape를 다시 구해보았습니다 
    - 1) original profet mape 비교 ( g4dn,p2,p3,g3s)  :  이전결과와 동일한지 비교
    - 2) old gpu 제외 (g4dn,g5,p2,a100,a10 ) :  오래된 gpu 인 p3,g3s는 제외하고 새로운 GPU도 추가한 상태
    - 3) original + old gpu ( g4dn,g5,p2,a100,a10,p2,g3s) :  지금까지 사용한 모든 GPU 사용

### < Name Clustering 비교 >

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/50091802/197953776-e74327fc-028f-4d2e-b672-753a3d54ca41.png">

### < 기존 profet mape와 모든 GPU 를 가지고 진행했을때 mape 비교 >
### ( 위에서 1번,2번, 3번케이스를 가지고 비교)
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/50091802/197956571-4edf5931-9d8b-44ea-8617-4abfd7afe609.png">

**Comment by kmu-leeky** [comment]
오케이 윤서야. 결국은 3번의 시나리오로 모든 gpu 를 사용해봐야 하지 않을까 싶기는 한데.. MAPE 의 경우 약간 더 높아진 경향은 있는듯 하네. 하드웨어 사양이 많이 변해서 그런건가. 지금도 크게 높아보이지는 않지만. 인스턴스 타입 추가 좋고, 추가로 이전에 나왔던 코멘트 중 name clustering 관련한 내용을 먼저 정리해볼래? 해당 내용을 커버하는 모듈 혹은 실험 결과가 추가하는 방향으로 진행이 되어야 할것 같아.

**Comment by hyoonseo159357** [comment]
넵,이전에 Name clustering 관련하여 코멘트들을 모두모아 빠르게 정리해보도록 하겠습니다

**Comment by hyoonseo159357** [comment]
## PROFET 리뷰 정리
### [ NAME CLUSTERING 관련 리뷰모음 ]

- 사용자가 operation 이름을 임의로 바꿀경우 문제가 발생한다
    - 전혀 상관없는 operation끼리 묶일수도 있다.

    `→ 개선방안 : 묶인 operation들 끼리의 연관관계를 조금더 자세히 설명 가능`
    
- 간단함, 견고하지않다, 확장시 일반화하기 어렵다 라는 평가
    - multi gpu로 확장, RNN 같은 모델로의 확장시에도 일반화할수 있어야함
    
    `→ 개선방안 : Name clustering이 간단하고, operation이름이 바뀔경우같은것도 고려하여 추가적인 방법을 덧붙여야할 필요성이 있음.`

    `→ 개선방안 : 모델별로 layer 종류나 갯수는 바뀌지않기 때문에, 갯수로 어떤 operation인지 구분하여 바뀐 operation이름들은 기존 operation 이름으로 바꿔버리기`

    `→  개선방안 : operation별로 걸린 latency 와 hardware gpu간의 상관관계를 분석하여 operation을 하드웨어 피처로 대체?`

    
- operation 뿐만 아니라 GPU 특성들도 같이 고려를 권함
    - nvidia-smi, nvprof, nsigt같은 하드웨어 프로파일러를 권함
    - 네트워크 대역폭, 주파수 등등 다른 요소들도 같이 고려하는걸 권함
    
    `→ 개선방안 : hardware profiler결과도 같이 포함하거나, 하드웨어 요소들을 더해도 괜찮을것`
    

### [ 그외에 공통적으로 많았던 리뷰들 ]

- only CNN
    
    `→ 개선방안 : 최신 CNN 모델들도 추가해볼것`
    
    `→ 개선방안 : CNN 외 모델들도 시도`
    
- only 단일 GPU
    
    `→ 개선방안 : multi gpu일때도 고려`
    
- only tensorflow
- 훈련 데이터의 다양성이 부족
    
    `→ 개선방안 : 훈련데이터을 다양화하여 추가 프로파일링 가능`

**Comment by kmu-leeky** [comment]
오케이. 윤서야 정리 땡큐. name clustering 위주로 해서 내일 같이 이야기를 나눠보자.
